cmake_minimum_required(VERSION 3.16)

if(ESP_PLATFORM)
    include(${CMAKE_CURRENT_LIST_DIR}/tools/esp-idf/component.cmake)
else()
    project(embr-meta)
    include(tools/cmake/setvars.cmake)
    add_subdirectory(${CMAKE_CURRENT_LIST_DIR}/src embr)
    add_subdirectory(${CMAKE_CURRENT_LIST_DIR}/test/catch catch)
endif()
