#pragma once

#if ESP_PLATFORM
#include <sdkconfig.h>
#endif

#if CONFIG_EMBR_GLOBAL_GC_STORAGE_SZ
#define FEATURE_EMBR_GLOBAL_GC 1
#define EMBR_GLOBAL_GC_STORAGE_SIZE CONFIG_EMBR_GLOBAL_GC_STORAGE_SZ
#define EMBR_GLOBAL_GC_HANDLE_SIZE CONFIG_EMBR_GLOBAL_GC_HANDLE_SZ
#endif
