#pragma once

// From IDF (TBD)
#if CONFIG_EMBR_GLOBAL_GC_STORAGE_SZ
#endif

#ifndef FEATURE_EMBR_GLOBAL_GC
#define FEATURE_EMBR_GLOBAL_GC 1
#define EMBR_GLOBAL_GC_STORAGE_SIZE 512
#define EMBR_GLOBAL_GC_HANDLE_SIZE 8
#endif
