set(SOURCES
        bits.cpp
        ble.cpp
        delegate-queue.cpp
        dsp.cpp
        lwip.cpp
        misc.cpp
        objlist.cpp
        observer.cpp
        setup.cpp
        word.cpp
        )