set(SOURCES
        bits.cpp
        bipbuf.cpp
        ble.cpp
        delegate-queue.cpp
        dsp.cpp
        lwip.cpp
        mem.cpp
        misc.cpp
        objlist.cpp
        observer.cpp
        scheduler.cpp
        setup.cpp
        thunk.cpp
        word.cpp
        )