config BOARD_ESP32_ESP_WROVER_KIT_41
    bool "Espressif ESP32 Wrover Kit 4.1"

config BOARD_ESP32_CYD
    bool "Cheap Yellow Display"

config BOARD_ESP32_LOPY
    bool "LoPy"

config BOARD_ESP32_M5_BASIC_CORE_V2_6
    bool "M5 Basic Core v2.6"
    help
        https://docs.m5stack.com/en/core/basic
        https://docs.m5stack.com/en/core/BASIC%20v2.6

config BOARD_ESP32_M5_BASIC_CORE_V2_7
    bool "M5 Basic Core v2.7"
    help
        https://docs.m5stack.com/en/core/basic_v2.7

config BOARD_ESP32_M5_TIMER_CAMERA_X
    bool "M5 Timer Camera X"

config BOARD_ESP32_WEMOS_MINI32
    bool "Wemos Mini32 D1 (ESP32)"
