config BOARD_ESP32S3_ADAFRUIT_FEATHER_REVTFT
    bool "Adafruit Feather Reverse TFT"

config BOARD_ESP32S3_FREENOVE
    bool "FreeNove ESP32S3 CAM"

# https://www.elecrow.com/crowpanel-esp32-2-13-e-paper-hmi-display-with-122-250-resolution-black-white-color-driven-by-spi-interface.html
config BOARD_ESP32S3_ELECROW_CROWPANEL_2_13
    bool "Elecrow CrowPanel 2.13inch E-paper"

config BOARD_ESP32S3_LILYGO_TCAM_S3
    bool "LILYGO T-Camera S3"

config BOARD_ESP32S3_LILYGO_T_QT_PRO
    bool "LILYGO T-QT Pro"

config BOARD_ESP32S3_LILYGO_T5_EINK_2_3
    bool "LILYGO T5 4.7in E-Ink v2.3"

config BOARD_ESP32S3_REJSACAN_V3_1
    bool "Magnus Thome's RejsaCAN v3.1"

config BOARD_ESP32S3_SEEED_XIAO
    bool "Seeed Studio Xiao ESP32S3 (Sense)"

config BOARD_ESP32S3_UM_BLING
    bool "Unexpected Maker BLING!"

config BOARD_ESP32S3_UM_FEATHERS3
    bool "Unexpected Maker FeatherS3"

config BOARD_ESP32S3_WAVESHARE_AMOLED_1_91
    bool "Waveshare AMOLED 1.91 inch"

# https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-4.3
config BOARD_ESP32S3_WAVESHARE_LCD_4_3
    bool "Waveshare LCD 4.3 inch"
