name: CMake

on:
  push:
    branches: [ "feat/**", "alpha" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    env:
      unit_test_dir: ${{github.workspace}}/test/catch

    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        compiler:
          - name: gcc
            c: gcc
            cxx: g++
          - name: llvm
            c: clang-18
            cxx: clang++-18
        release: ["Debug", "Release"]

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Setup Clang
      if: matrix.compiler.name == 'clang'
      uses: egor-tensin/setup-clang@v1
      with:
        version: 18

    - name: Build
      uses: threeal/cmake-action@v2.1.0
      with:
        source-dir: ${{env.unit_test_dir}}
        options: >
          CMAKE_C_COMPILER=${{ matrix.compiler.c }}
          CMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }}
          CMAKE_BUILD_TYPE=${{ matrix.release }}

    - name: Test
      uses: threeal/ctest-action@v1.1.0
      with:
        # DEBT: Grab "build-dir" from above cmake-action
        test-dir: ${{env.unit_test_dir}}/build

