name: ESP-IDF

on:
  push:
    branches: [ "feat/**", "alpha" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # DEBT: Pretty obnoxious way to get at managed component, but it will do
      ESTD_ROOT:  managed_components/malachi-iot__estd

    strategy:
      fail-fast: false
      matrix:
        version: [v5.4.4, v5.5.4, v6.0.1]
        # 06MAY25 - esp32p4 has odd sdkconfig glitch, may be related to our
        # sdkconfig override below (I don't think so though)
        target: [esp32, esp32s3, esp32c3, esp32c6]
        include:
        - version: v6.0.1
          target: esp32
          qemu: true
        # Almost works but nothing past bootloader seems to visibly run.
        # No RTOS or Unity output appears, seems to hang.
        #- version: v6.0.1
        #  target: esp32c3
        #  qemu: true
        - version: v6.0.1
          target: esp32s3
          qemu: true

    steps:
    - name: Checkout repo
      uses: actions/checkout@v6
    - name: qemu option prep
      if: matrix.qemu
      run: |
        cat >> $GITHUB_ENV <<EOF
        BUILD_OPT="-DSDKCONFIG_DEFAULTS=sdkconfig.defaults.ci;sdkconfig.defaults"
        EOF
    - name: "build"
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ matrix.version }}
        target: ${{ matrix.target }}
        path: 'test/esp-idf/unity'
        command: "idf.py build ${{ env.BUILD_OPT }}"
    - name: "qemu"
      # Usually only takes a few seconds to run
      timeout-minutes: 1
      if: matrix.qemu
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ matrix.version }}
        target: ${{ matrix.target }}
        path: 'test/esp-idf/unity'
        # IDF 6.0+ gives us pass through to no-reboot
        command: idf.py qemu --qemu-extra-args="-no-reboot" | tee qemu_output.txt
    #- name: "qemu output inspection"
    #  if: ${{ matrix.qemu }}
    #  run: cat test/esp-idf/unity/qemu_output.txt | "${env.ESTD_ROOT}/tools/esp-idf/unity-gh-action.py"

